### ISSUE TITLE
[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. 

### ISSUE THREAD

**Issue by Aaronliu2016** [vueup/vueup-quill#409] opened 2023-08-02 11:50 UTC
Chrome console shows this warning information:
> [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (<URL>) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

Is this caused by the quill.js version?

**Comment by axolo** [comment] 2023-08-03 06:12
https://github.com/quilljs/quill/issues/3806 
update quill to 2.0.0

**Comment by leeobrum** [comment] 2023-08-04 18:14
hello, any predictions for an update to version 2.0?

**Comment by AnthonyRuelle** [comment] 2023-08-16 15:31
Hello, same problem here, any news ?

**Comment by mageshk98** [comment] 2023-08-18 14:34
Facing performance issues because of this! An update would be helpful

**Comment by antrmarq** [comment] 2023-08-21 18:49
Any update on this?

**Comment by leeobrum** [comment] 2023-08-28 18:54
> [quilljs/quill#3806](https://github.com/quilljs/quill/issues/3806) update quill to 2.0.0

hi, any predictions for an update to version 2.0?

**Comment by YouSour** [comment] 2023-08-29 04:45
got the same issue.

**Comment by Aaronliu2016** [comment] 2023-08-29 09:20
Have to switch to tiptap instead of quill. Not as easy as vue-quill but the vue3 sample of tiptap is really clear.
guess what, its performance is way much better.

**Comment by JelynValcorza** [comment] 2023-08-30 07:21
I got the same issue on vue-quill, can someone recommend rich text editor that can embed video from youtube or any other media sites which will be compatible to vue js 3

**Comment by rahul37865** [comment] 2023-09-01 12:59
I am getting this warning on Firefox `Use of Mutation Events is deprecated. Use MutationObserver instead.`
On google Chrome Warning is 
`[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.`

Where exactly we need to use MutationObserver Or quick fix update will be great. We urgently need to fix this people are moving to other editor due to this warning.

**Comment by geekyshow1** [comment] 2023-09-01 13:08
On Google Chrome warning is
`[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.`

**Comment by tyfiero** [comment] 2023-09-06 18:19
Also having this issue with vanilla js quil. Really need to fix this quick plz, or I'll have to move to a different editor.

Error is coming from this line in the following code:

 _this.domNode.addEventListener('DOMNodeInserted', function() {});
 
 
```
var Scroll = function(_Parchment$Scroll) {
                    _inherits(Scroll, _Parchment$Scroll);

                    function Scroll(domNode, config) {
                        _classCallCheck(this, Scroll);

                        var _this = _possibleConstructorReturn(this, (Scroll.__proto__ || Object.getPrototypeOf(Scroll)).call(this, domNode));

                        _this.emitter = config.emitter;
                        if (Array.isArray(config.whitelist)) {
                            _this.whitelist = config.whitelist.reduce(function(whitelist, format) {
                                whitelist[format] = true;
                                return whitelist;
                            }, {});
                        }
                        // Some reason fixes composition issues with character languages in Windows/Chrome, Safari
                        _this.domNode.addEventListener('DOMNodeInserted', function() {});
                        _this.optimize();
                        _this.enable();
                        return _this;
                    }
```

**Comment by lqmorais** [comment] 2023-09-15 13:12
The line `_this.domNode.addEventListener('DOMNodeInserted', function () {});` appears to be a workaround to trigger some internal logic in response to changes in the DOM when new nodes are inserted into `_this.domNode`. However, the empty function doesn't actually perform any meaningful action.

An equivalent using `MutationObserver` will be something like this: 

```
var observer = new MutationObserver(function () {});
observer.observe(_this.domNode, { childList: true });
```

childList when set to true, indicates that the observer should monitor changes to the direct children (added or removed nodes) of the target node.

I tried this and the warning is gone. Apparently all works as expected.

**Comment by sharpprahs** [comment] 2023-10-03 01:40
same problem

**Comment by leonid-br** [comment] 2023-10-13 07:51
Hello. Tell me, is there a plan to fix this error?

**Comment by messenjer** [comment] 2023-10-13 08:33
The solution would be to upgrade to version 2 of [quill](https://github.com/quilljs/quill), but it hasn't been released yet https://github.com/quilljs/quill/issues/3806

**Comment by JelynValcorza** [comment] 2023-10-16 08:35
The problem is we have no updates on the promised version 2 of Quill. Just use Tiptap instead

**Comment by leonid-br** [comment] 2023-10-16 15:51
> The problem is we have no updates on the promised version 2 of Quill. Just use Tiptap instead

Your suggestion is to replace quill throughout the project?

**Comment by Spring-SWE** [comment] 2023-11-04 18:29
There should be an update soon, the developer hoping to release a beta before December.
https://github.com/quilljs/quill/issues/3896

**Comment by Anveshh99** [comment] 2023-11-23 06:15
[Deprecation] Listener added for a synchronous DC" Mutation Event. This event type is deprecated quill..
and work is underway to remove it from this browser. usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. consider using
MutationObserver instead ......Unable to perform some functionality because of this! An update or help would be helpful

**Comment by digitalboy** [comment] 2023-12-03 09:38
> [quilljs/quill#3806](https://github.com/quilljs/quill/issues/3806) update quill to 2.0.0

只能等待了……

**Comment by Leroy-sama** [comment] 2023-12-25 14:03
still no update to quill. I'm using tiptap but you have to import almost everything.

**Comment by EdManukyan** [comment] 2023-12-29 21:55
Hello guys, any update on when is the new version release going to happen and is this issue with the mutation going to be fixed?

**Comment by Philword** [comment] 2023-12-30 04:30
Hey guys also waiting for the update.

**Comment by chinahmz** [comment] 2024-01-04 02:21
> The line `_this.domNode.addEventListener('DOMNodeInserted', function () {});` appears to be a workaround to trigger some internal logic in response to changes in the DOM when new nodes are inserted into `_this.domNode`. However, the empty function doesn't actually perform any meaningful action.
> 
> An equivalent using `MutationObserver` will be something like this:
> 
> ```
> var observer = new MutationObserver(function () {});
> observer.observe(_this.domNode, { childList: true });
> ```
> 
> childList when set to true, indicates that the observer should monitor changes to the direct children (added or removed nodes) of the target node.
> 
> I tried this and the warning is gone. Apparently all works as expected.

This method works. Thank you!

**Comment by proniket** [comment] 2024-01-04 13:27
Hey everyone, still waiting for fixes in the new version of react-quill.. is there any updates.. on when this error is going to be fixed "[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event."

**Comment by Wamaitha12** [comment] 2024-01-09 12:03
> Hey everyone, still waiting for fixes in the new version of react-quill.. is there any updates.. on when this error is going to be fixed "[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event."

I thought you found the solution?

**Comment by shanulhabib** [comment] 2024-01-09 13:37
Hey I am also facing this error let us know if someone find the solution for this.

**Comment by hannes1337** [comment] 2024-01-11 23:08
same here, standing in line and waiting.

**Comment by 15083325286** [comment] 2024-01-16 06:46
Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

**Comment by Lnyyy6** [comment] 2024-01-16 06:55
iListener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

i have the same problem
Any solution now？

**Comment by zran-20** [comment] 2024-01-19 09:17
I met the same prompt. Not sure what the impact is.

**Comment by Seanniie** [comment] 2024-01-22 08:28
me using V2.0.0.. but same issue

**Comment by GisungJung** [comment] 2024-01-22 08:30
me too i have same issue

**Comment by luin** [comment] 2024-01-22 12:00
Hi 👋 

I'm the maintainer of Quill, and we just released the second beta version of Quill 2.0. This version is considered feature-complete, and I wanted to know if there's anything I can do to help the transition to Quill 2.0.

There are many performance improvements made in Quill 2.0 and the dev/beta version has already been running on [Slab](https://slab.com/) for more than one year without any major issues. The version also avoids Mutation Event at all so should solve the issue.

We are still working on the documentation and examples, but https://v2.quilljs.com/ already contains useful info for upgrading to 2.0.

**Comment by Lnyyy6** [comment] 2024-01-23 07:49
@luin i want to know this plugin vue-quill is maintained by you This plugin doesn't seem to introduce quill 2.0 . How to solve it？

**Comment by GisungJung** [comment] 2024-01-24 23:41
i'm using react-quill v2.0 warning message still appear

**Comment by luin** [comment] 2024-01-25 01:25
@GisungJung react-quill v2.0 uses Quill v1 so that's the reason you still saw the warning.

**Comment by Cz2545481217** [comment] 2024-01-29 04:13
> @GisungJungReact-quill v2.0 使用 Quill v1，所以这就是您仍然看到警告的原因。

When to upgrade React Quill built-in Quill to Quill2？

**Comment by Cz2545481217** [comment] 2024-01-29 04:13
> @GisungJungReact-quill v2.0 使用 Quill v1，所以这就是您仍然看到警告的原因。

When to upgrade React Quill built-in Quill to Quill2

**Comment by Cz2545481217** [comment] 2024-01-29 04:14
> @GisungJungReact-quill v2.0 使用 Quill v1，所以这就是您仍然看到警告的原因。

When to upgrade React Quill built-in Quill to Quill2？

**Comment by ArsalanAli915** [comment] 2024-01-30 14:50
```%%javascript
%%javascript

require.config({
  paths: {
    d3: '//cdnjs.cloudflare.com/ajax/libs/d3/5.15.0/d3.min',
    am5: '//www.amcharts.com/lib/5/index',
    am5percent: '//www.amcharts.com/lib/5/percent',
    exporting: '//www.amcharts.com/lib/5/plugins/exporting',
    'am5themes_Animated': '//www.amcharts.com/lib/5/themes/Animated',
  },
  shim: {
    am5: {
      init: function () {
        return am5;
      }
    },
    am5percent: {
      deps: ['am5'],
      exports: 'am5xy',
      init: function () {
        return am5percent;
      }
    },
    exporting: {
      deps: ['am5'],
      exports: 'am5plugins_exporting',
      init: function () {
        return am5plugins_exporting;
      }
    },
    'am5themes_Animated': {
      deps: ['am5'],
      init: function () {
        return am5themes_Animated;
      }
    }
  }
});

element.append('<div id="chartdiv" style="height: 500px;"></div>');
require(['am5', 'am5percent', 'am5themes_Animated', 'exporting'], function (am5, am5percent, am5themes_Animated, exporting) {
  var root = am5.Root.new("chartdiv");

  root.setThemes([
    am5themes_Animated.new(root)
  ]);

  var chart = root.container.children.push(
    am5percent.PieChart.new(root, {})

  );

  // Create 
  var series = chart.series.push(
    am5percent.PieSeries.new(root, {
      name: "Series",
      categoryField: "country",
      valueField: "litres"
    })
  );

  // Define data
  series.data.setAll([{
    "country": "Lithuania",
    "litres": 9501.9
  }, {
    "country": "Czech Republic",
    "litres": 301.9
  }, {
    "country": "Ireland",
    "litres": 201.1
  }, {
    "country": "Germany",
    "litres": 165.8
  }, {
    "country": "Australia",
    "litres": 139.9
  }, {
    "country": "Austria",
    "litres": 128.3
  }, {
    "country": "UK",
    "litres": 99
  }, {
    "country": "Belgium",
    "litres": 60
  }, {
    "country": "The Netherlands",
    "litres": 50
  }]);

//   var title = chart.children.unshift(am5.Label.new(root, {
//     text: "Sales by country ($M)",
//     fontSize: 24,
//     textAlign: "center",
//     width: am5.p100,
//     visible: false
//   }));

  // Export the chart as PNG
    // Enable exporting
    var exportings = am5plugins_exporting.Exporting.new(root, {
      menu: am5plugins_exporting.ExportingMenu.new(root, {}),
      pngOptions: {
        maintainPixelRatio: true
      },
    });
    exportings.export()

}, function (err) {
  console.log(err);
});


```

**Comment by ArsalanAli915** [comment] 2024-01-30 14:51
````%%javascript
%%javascript

require.config({
  paths: {
    d3: '//cdnjs.cloudflare.com/ajax/libs/d3/5.15.0/d3.min',
    am5: '//www.amcharts.com/lib/5/index',
    am5percent: '//www.amcharts.com/lib/5/percent',
    exporting: '//www.amcharts.com/lib/5/plugins/exporting',
    'am5themes_Animated': '//www.amcharts.com/lib/5/themes/Animated',
  },
  shim: {
    am5: {
      init: function () {
        return am5;
      }
    },
    am5percent: {
      deps: ['am5'],
      exports: 'am5xy',
      init: function () {
        return am5percent;
      }
    },
    exporting: {
      deps: ['am5'],
      exports: 'am5plugins_exporting',
      init: function () {
        return am5plugins_exporting;
      }
    },
    'am5themes_Animated': {
      deps: ['am5'],
      init: function () {
        return am5themes_Animated;
      }
    }
  }
});

element.append('<div id="chartdiv" style="height: 500px;"></div>');
require(['am5', 'am5percent', 'am5themes_Animated', 'exporting'], function (am5, am5percent, am5themes_Animated, exporting) {
  var root = am5.Root.new("chartdiv");

  root.setThemes([
    am5themes_Animated.new(root)
  ]);

  var chart = root.container.children.push(
    am5percent.PieChart.new(root, {})

  );

  // Create 
  var series = chart.series.push(
    am5percent.PieSeries.new(root, {
      name: "Series",
      categoryField: "country",
      valueField: "litres"
    })
  );

  // Define data
  series.data.setAll([{
    "country": "Lithuania",
    "litres": 9501.9
  }, {
    "country": "Czech Republic",
    "litres": 301.9
  }, {
    "country": "Ireland",
    "litres": 201.1
  }, {
    "country": "Germany",
    "litres": 165.8
  }, {
    "country": "Australia",
    "litres": 139.9
  }, {
    "country": "Austria",
    "litres": 128.3
  }, {
    "country": "UK",
    "litres": 99
  }, {
    "country": "Belgium",
    "litres": 60
  }, {
    "country": "The Netherlands",
    "litres": 50
  }]);

//   var title = chart.children.unshift(am5.Label.new(root, {
//     text: "Sales by country ($M)",
//     fontSize: 24,
//     textAlign: "center",
//     width: am5.p100,
//     visible: false
//   }));

  // Export the chart as PNG
    // Enable exporting
    var exportings = am5plugins_exporting.Exporting.new(root, {
      menu: am5plugins_exporting.ExportingMenu.new(root, {}),
      pngOptions: {
        maintainPixelRatio: true
      },
    });
    exportings.export()

}, function (err) {
  console.log(err);
});


````

**Comment by asultanov** [comment] 2024-02-04 19:56
Find this line

```
_this.domNode.addEventListener('DOMNodeInserted', function () {});
```
Select it and replace with

```
    let observer = new MutationObserver(function (mutations) {
        //mutations.forEach(function (mutation) {
        // Обработка изменений в DOM
        //console.log(mutation);
        //});
    });

    // Настройка на отслеживание изменений в документе
    let observerConfig = {childList: true, subtree: true};
    observer.observe(_this.domNode, observerConfig);
```

**Comment by JParedes98** [comment] 2024-02-24 02:08
Any updates here?

**Comment by FelipeKreulich** [comment] 2024-02-25 00:13
I'm facing the same problem, even with quill updated to version 2.0.0, I tried a few things, but without success

**Comment by v01** [comment] 2024-02-27 02:20
Solution:
 
1. Find this line: _this.domNode.addEventListener('DOMNodeInserted', function () {}); let observerConfig = {childList: true, subtree: true};

2. Select it and replace with:
  observer.observe(_this.domNode, observerConfig);
    _this.optimize();
    _this.enable();
    return _this;
  }

**Comment by FelipeKreulich** [comment] 2024-02-27 10:45
> Solution:
> 
> 1. Find this line: _this.domNode.addEventListener('DOMNodeInserted', function () {}); let observerConfig = {childList: true, subtree: true};
> 2. Select it and replace with:
>    observer.observe(_this.domNode, observerConfig);
>    _this.optimize();
>    _this.enable();
>    return _this;
>    }

It's working for me, Thanks!

**Comment by leonid-br** [comment] 2024-02-27 11:06
> Solution:
> 
> 1. Find this line: _this.domNode.addEventListener('DOMNodeInserted', function () {}); let observerConfig = {childList: true, subtree: true};
> 2. Select it and replace with:
>    observer.observe(_this.domNode, observerConfig);
>    _this.optimize();
>    _this.enable();
>    return _this;
>    }

and do you want to update this manually every time you clone a project?

**Comment by AnthonyRuelle** [comment] 2024-02-28 16:05
> > Solution:
> > 
> > 1. Find this line: _this.domNode.addEventListener('DOMNodeInserted', function () {}); let observerConfig = {childList: true, subtree: true};
> > 2. Select it and replace with:
> >    observer.observe(_this.domNode, observerConfig);
> >    _this.optimize();
> >    _this.enable();
> >    return _this;
> >    }
> 
> and do you want to update this manually every time you clone a project?

you could possibly make a patch but that's really not the right way to do it. The package author should include this fix!

**Comment by JParedes98** [comment] 2024-02-28 17:27
I ended up using quill core library and creating my own component. I know is not the best thing around, but at least works.

If someone uses, remember to copy the quill css styles and snow theme to laravel webpack/vite css compiler.

[TextEditor.txt](https://github.com/vueup/vue-quill/files/14438047/TextEditor.txt)

**Comment by oza95** [comment] 2024-03-07 06:14
[Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (<URL>) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.    Any solution for this I am using it in NextJS

**Comment by dandanbang** [comment] 2024-04-03 02:27
the message disappears now after using 2.0.0

    
    <script defer src="https://cdn.jsdelivr.net/npm/quill@2.0.0-rc.4/dist/quill.js"></script>

**Comment by daniloribeiro00** [comment] 2024-04-18 14:22
With the release of Quill 2.0 (https://github.com/quilljs/quill/releases/tag/v2.0.0), will this library be updated to support it?

**Comment by ericktreichel** [comment] 2024-04-19 13:55
They finally released Quill 2.0 https://github.com/quilljs/quill/releases/tag/v2.0.0
Any idea about updating this lib to too and fix this problem? 
Thanks

**Comment by Wellitonzs** [comment] 2024-04-29 18:59
I'm facing this same warning in my React application. Any expected fix for this problem?

**Comment by luin** [comment] 2024-04-30 00:25
@Wellitonzs For React you can use Quill without a library/framework: https://quilljs.com/playground/react

**Comment by noxsii** [comment] 2024-05-10 15:07
push...

**Comment by alekswebnet** [comment] 2024-05-13 12:25
For Vue 3 and Quill 2 you could try this simple wrapper component: https://github.com/alekswebnet/vue-quilly

**Comment by strukovd** [comment] 2024-05-14 09:27
Исправьте это говно 💩

**Comment by Sky-Breaker07** [comment] 2024-06-09 11:24
Just go to your terminal and install the latest version of quill
Then go to your package.json and add:
"overrides": {
    "quill": "^2.0.2"
  }
  
  Then uninstall @vueup/vue-quill package
  Then install it again.
  The error will be resolved

**Comment by ErikVerheul** [comment] 2024-06-09 15:43
@Sky-Breaker07 : Thanks for the tip. It worked as expected! Saved me a lot of work forking and changing vue-quill.

**Comment by SanjuBalasubramani** [comment] 2024-06-19 09:33
> var observer = new MutationObserver(function () {});
> observer.observe(_this.domNode, { childList: true });

**Comment by reqwire** [comment] 2024-07-03 21:47
I would like to update to quill 2 but It's too buggy. :/

**Comment by fedottt** [comment] 2024-07-06 05:03
> Just go to your terminal and install the latest version of quill Then go to your package.json and add: "overrides": { "quill": "^2.0.2" }
> 
> Then uninstall @vueup/vue-quill package Then install it again. The error will be resolved

didnt work

added to npm/package.json overrides block does error on **audit fix**

```shell
# npm audit
npm error code EOVERRIDE
npm error Override for quill@2.0.2 conflicts with direct dependency
npm error A complete log of this run can be found in: /_logs/2024-07-06T04_54_41_286Z-debug-0.log
``` 

even with **"overrides": { "quill": "2.0.2" }** or edit **dependencies** block to **"quill": "^2.0.2"** didnt do the trick

after fresh install vue-quill error is still here (damn) and in dependencies we see quill 1.3.7

**Closed as completed** 2024-09-13 00:35 UTC
Labels: wontfix

**Comment by leo-google-custom-search** [comment] 2025-02-03 08:38
@Aaronliu2016 https://jquerys.space/questions/the-replacewith-method-fails-to-function-properly-when-used-in-conjunction-with-the
