### ISSUE TITLE
Listener added for a 'DOMNodeInserted' mutation event. This event type is deprecated, and will be removed from this browser very soon. Usage of this event listener will cause performance issues today, and represents a large risk of future site breakage. Consider using MutationObserver instead.

### ISSUE THREAD

**Issue by happyBodyBymj** [vueup/vueup-quill#531] opened 2024-03-27 06:10 UTC

**Comment by iamaks1993** [comment] 2024-03-29 11:51
I am facing the same issue.

**Comment by downey-lv** [comment] 2024-03-31 18:07
Duplicate of #409

**Closed as completed** 2024-06-07 17:25 UTC
Labels: wontfix
