### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by iamaks1993** [vueup/vueup-quill#525] opened 2024-03-18 14:05 UTC
**Version**
@vueup/vue-quill version [e.g. 1.2]

**Describe the bug**
Getting deprecation warning message when any state changes.  

dom.ts:107 [Deprecation] Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (https://w3c.github.io/uievents/#legacy-event-types) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

**Comment by downey-lv** [comment] 2024-03-31 18:07
Duplicate of #409

**Closed as completed** 2024-06-07 17:25 UTC
Labels: wontfix
